id: intelligent-monitor
namespace: sentinel

tasks:
  # Debug log to confirm the flow runs every 30 seconds
  - id: debug-start
    type: io.kestra.plugin.core.log.Log
    message: "==== SENTINEL execution tick - {{ execution.id }} - {{ now() }} ===="

  # 1. Fetch Health Data (Parallel)
  - id: fetch-metrics
    type: io.kestra.plugin.core.flow.Parallel
    allowFailure: true
    tasks:
      - id: get-auth
        type: io.kestra.plugin.core.http.Request
        uri: http://auth-service:3001/health
        allowFailure: true

      - id: get-payment
        type: io.kestra.plugin.core.http.Request
        uri: http://payment-service:3002/health
        allowFailure: true

      - id: get-notify
        type: io.kestra.plugin.core.http.Request
        uri: http://notification-service:3003/health
        allowFailure: true


  # 2. Check if any service is down
  - id: check-failures
    type: io.kestra.plugin.core.flow.If
    condition: >
      {{ 
        (outputs['get-auth'].code | default(500)) != 200 or
        (outputs['get-payment'].code | default(500)) != 200 or
        (outputs['get-notify'].code | default(500)) != 200
      }}
    then:
      - id: log-failure-detected
        type: io.kestra.plugin.core.log.Log
        message: "âš ï¸ FAILURE DETECTED - Starting auto-healing process..."

    else:
      - id: log-healthy
        type: io.kestra.plugin.core.log.Log
        message: "âœ… All services healthy - System Normal"

  # 3. Auto-healing for Auth Service
  - id: heal-auth
    type: io.kestra.plugin.core.flow.If
    condition: "{{ (outputs['get-auth'].code | default(500)) != 200 }}"
    then:
      - id: log-auth-healing
        type: io.kestra.plugin.core.log.Log
        message: "ðŸš‘ AUTH SERVICE DOWN - HEALING NOW..."
      - id: restart-auth
        type: io.kestra.plugin.core.http.Request
        uri: http://auth-service:3001/simulate/healthy
        method: POST
        allowFailure: true
      - id: log-auth-healed
        type: io.kestra.plugin.core.log.Log
        message: "âœ… AUTH SERVICE HEALED!"

  # 4. Auto-healing for Payment Service
  - id: heal-payment
    type: io.kestra.plugin.core.flow.If
    condition: "{{ (outputs['get-payment'].code | default(500)) != 200 }}"
    then:
      - id: log-payment-healing
        type: io.kestra.plugin.core.log.Log
        message: "ðŸš‘ PAYMENT SERVICE DOWN - HEALING NOW..."
      - id: restart-payment
        type: io.kestra.plugin.core.http.Request
        uri: http://payment-service:3002/simulate/healthy
        method: POST
        allowFailure: true
      - id: log-payment-healed
        type: io.kestra.plugin.core.log.Log
        message: "âœ… PAYMENT SERVICE HEALED!"

  # 5. Auto-healing for Notification Service
  - id: heal-notify
    type: io.kestra.plugin.core.flow.If
    condition: "{{ (outputs['get-notify'].code | default(500)) != 200 }}"
    then:
      - id: log-notify-healing
        type: io.kestra.plugin.core.log.Log
        message: "ðŸš‘ NOTIFICATION SERVICE DOWN - HEALING NOW..."
      - id: restart-notify
        type: io.kestra.plugin.core.http.Request
        uri: http://notification-service:3003/simulate/healthy
        method: POST
        allowFailure: true
      - id: log-notify-healed
        type: io.kestra.plugin.core.log.Log
        message: "âœ… NOTIFICATION SERVICE HEALED!"

  # 6. AI Analysis (Optional - only if API key is set)
  - id: ai-analysis
    type: io.kestra.plugin.core.flow.If
    condition: >
      {{ 
        (outputs['get-auth'].code | default(500)) != 200 or
        (outputs['get-payment'].code | default(500)) != 200 or
        (outputs['get-notify'].code | default(500)) != 200
      }}
    then:
      - id: call-ai
        type: io.kestra.plugin.core.http.Request
        uri: https://api.groq.com/openai/v1/chat/completions
        method: POST
        allowFailure: true
        headers:
          Authorization: "Bearer {{ secret('GROQ_API_KEY') }}"
          Content-Type: "application/json"
        body: |
          {
            "model": "llama-3.3-70b-versatile",
            "messages": [
              {
                "role": "system",
                "content": "You are Sentinel, a DevOps AI. Analyze service health and provide concise status: HEALTHY, DEGRADED, or CRITICAL with brief reasoning."
              },
              {
                "role": "user",
                "content": "Service Health Check Results:\n- Auth: {{ outputs['get-auth'].code | default('DOWN') }}\n- Payment: {{ outputs['get-payment'].code | default('DOWN') }}\n- Notification: {{ outputs['get-notify'].code | default('DOWN') }}\n\nAnalyze the overall system health."
              }
            ],
            "temperature": 0.3,
            "max_tokens": 150
          }

      - id: log-ai-result
        type: io.kestra.plugin.core.log.Log
        message: |
          ðŸ¤– SENTINEL AI REPORT:
          {{ outputs['call-ai'].body | jq(".choices[0].message.content") | first | default("AI analysis unavailable") }}

  # 7. Push status to dashboard
  - id: push-to-dashboard
    type: io.kestra.plugin.core.http.Request
    uri: http://host.docker.internal:4000/api/kestra-webhook
    method: POST
    contentType: application/json
    allowFailure: true
    body: |
      {% set auth = outputs['get-auth'] | default({}) %}
      {% set payment = outputs['get-payment'] | default({}) %}
      {% set notify = outputs['get-notify'] | default({}) %}
      {% set aiReport = outputs['call-ai'].body | jq(".choices[0].message.content") | first | default("System monitoring active - Auto-healing enabled") %}

      {
        "aiReport": {{ aiReport | json }},
        "metrics": {
          "auth": { "code": {{ auth.code | default(500) }} },
          "payment": { "code": {{ payment.code | default(500) }} },
          "notification": { "code": {{ notify.code | default(500) }} }
        }
      }


triggers:
  - id: monitor-schedule
    type: io.kestra.plugin.core.trigger.Schedule
    cron: "*/1 * * * *"
    timezone: "Asia/Kolkata"
